/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.inong_act2a;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author brix
 */
public class crud extends javax.swing.JFrame {

    /**
     * Creates new form crud
     */
    public crud() {
        initComponents();
        loadTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnclear = new javax.swing.JButton();
        btnadd = new javax.swing.JButton();
        btnupdate = new javax.swing.JButton();
        btndelete = new javax.swing.JButton();
        txtproduct_name = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtprice = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtquantity = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "PRODUCT NAME", "PRICE", "QUANTITY"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 100, 600, -1));

        btnclear.setBackground(new java.awt.Color(51, 255, 255));
        btnclear.setText("CLEAR");
        btnclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnclearActionPerformed(evt);
            }
        });
        getContentPane().add(btnclear, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 470, 130, 30));

        btnadd.setBackground(new java.awt.Color(0, 204, 204));
        btnadd.setText("ADD");
        btnadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddActionPerformed(evt);
            }
        });
        getContentPane().add(btnadd, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 330, 130, 30));

        btnupdate.setBackground(new java.awt.Color(51, 255, 255));
        btnupdate.setText("UPDATE");
        btnupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdateActionPerformed(evt);
            }
        });
        getContentPane().add(btnupdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 380, 130, 30));

        btndelete.setBackground(new java.awt.Color(51, 255, 255));
        btndelete.setText("DELETE");
        btndelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeleteActionPerformed(evt);
            }
        });
        getContentPane().add(btndelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 430, 130, 30));
        getContentPane().add(txtproduct_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, 150, -1));

        jLabel1.setText("ID");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, -1, -1));
        getContentPane().add(txtprice, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 240, 150, -1));

        jLabel2.setText("Price:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, -1, -1));
        getContentPane().add(txtquantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 270, 150, -1));

        jLabel3.setText("Quantity:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, -1, -1));
        getContentPane().add(txtID, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, 150, -1));

        jLabel4.setText("Product Name");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable1MouseClicked

    private void btnaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddActionPerformed
        // TODO add your handling code here:
       String name = txtproduct_name.getText().trim();
    String priceText = txtprice.getText().trim();
    String qtyText = txtquantity.getText().trim();

    // Check if fields are empty (excluding ID since it's automatic)
    if (name.isEmpty() || priceText.isEmpty() || qtyText.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Please fill in all fields.", "Input Warning", JOptionPane.WARNING_MESSAGE);
        return;
    }

    try {
        double price = Double.parseDouble(priceText);
        int quantity = Integer.parseInt(qtyText);

        // Omit ID column so MS Access assigns the AutoNumber automatically
        String sql = "INSERT INTO products (product_name, price, quantity) VALUES (?, ?, ?)";

        try (Connection conn = MSConnectAccess.conn();
             PreparedStatement pstmt = conn != null ? conn.prepareStatement(sql) : null) {

            if (conn == null) return;

            pstmt.setString(1, name);
            pstmt.setDouble(2, price);
            pstmt.setInt(3, quantity);

            int rowsInserted = pstmt.executeUpdate();
            if (rowsInserted > 0) {
                JOptionPane.showMessageDialog(this, "Product added successfully!");
                loadTable(); // Refresh table to display the new generated ID

                // Clear input fields
                txtID.setText("");
                txtproduct_name.setText("");
                txtprice.setText("");
                txtquantity.setText("");
                txtproduct_name.requestFocus();
            }
        }
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Price and Quantity must be valid numbers.", "Format Error", JOptionPane.ERROR_MESSAGE);
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Database Error: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_btnaddActionPerformed

    private void btnupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdateActionPerformed
        // TODO add your handling code here:
        String id = txtID.getText().trim();
    String name = txtproduct_name.getText().trim();
    String priceText = txtprice.getText().trim();
    String qtyText = txtquantity.getText().trim();

    if (id.isEmpty() || name.isEmpty() || priceText.isEmpty() || qtyText.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Please select a record or fill in all fields.", "Input Warning", JOptionPane.WARNING_MESSAGE);
        return;
    }

    try {
        double price = Double.parseDouble(priceText);
        int quantity = Integer.parseInt(qtyText);

        String sql = "UPDATE products SET product_name = ?, price = ?, quantity = ? WHERE ID = ?";

        try (Connection conn = MSConnectAccess.conn();
             PreparedStatement pstmt = conn != null ? conn.prepareStatement(sql) : null) {

            if (conn == null) return;

            pstmt.setString(1, name);
            pstmt.setDouble(2, price);
            pstmt.setInt(3, quantity);
            pstmt.setString(4, id);

            int rowsUpdated = pstmt.executeUpdate();
            if (rowsUpdated > 0) {
                JOptionPane.showMessageDialog(this, "Product updated successfully!");
                loadTable();

                txtID.setText("");
                txtproduct_name.setText("");
                txtprice.setText("");
                txtquantity.setText("");
                txtID.requestFocus();
            } else {
                JOptionPane.showMessageDialog(this, "Record with ID " + id + " not found.", "Update Failed", JOptionPane.WARNING_MESSAGE);
            }
        }
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Price and Quantity must be valid numbers.", "Format Error", JOptionPane.ERROR_MESSAGE);
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Database Error: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_btnupdateActionPerformed

    private void btndeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeleteActionPerformed
        // TODO add your handling code here:
        String id = txtID.getText().trim();

    // Check if ID is empty
    if (id.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Please select or enter the ID of the product to delete.", "Input Warning", JOptionPane.WARNING_MESSAGE);
        return;
    }

    // Confirmation dialog before deleting
    int confirm = JOptionPane.showConfirmDialog(this, 
            "Are you sure you want to delete product ID: " + id + "?", 
            "Confirm Delete", 
            JOptionPane.YES_NO_OPTION);

    if (confirm == JOptionPane.YES_OPTION) {
        String sql = "DELETE FROM products WHERE ID = ?";

        try (Connection conn = MSConnectAccess.conn();
             PreparedStatement pstmt = conn != null ? conn.prepareStatement(sql) : null) {

            if (conn == null) return;

            pstmt.setString(1, id);

            int rowsDeleted = pstmt.executeUpdate();
            if (rowsDeleted > 0) {
                JOptionPane.showMessageDialog(this, "Product deleted successfully!");
                loadTable(); // Refresh table from database

                // Clear input fields
                txtID.setText("");
                txtproduct_name.setText("");
                txtprice.setText("");
                txtquantity.setText("");
                txtID.requestFocus();
            } else {
                JOptionPane.showMessageDialog(this, "Record with ID " + id + " not found.", "Delete Failed", JOptionPane.WARNING_MESSAGE);
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Database Error: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    }//GEN-LAST:event_btndeleteActionPerformed

    private void btnclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnclearActionPerformed
        // TODO add your handling code here:
        txtID.setText("");
    txtproduct_name.setText("");
    txtprice.setText("");
    txtquantity.setText("");

    // Deselect any selected row in the JTable
    jTable1.clearSelection();

    // Reset cursor focus back to the ID field
    txtID.requestFocus();
    }//GEN-LAST:event_btnclearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(crud.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(crud.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(crud.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(crud.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new crud().setVisible(true);
                
            }
            
            
            
        });
        
        
        
    }
    
    private void loadTable() {
    javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) jTable1.getModel();
    model.setRowCount(0); // Clear existing table rows

    // SQL query (make sure 'Products' matches your Access table name)
    String sql = "SELECT * FROM products";

    try (Connection conn = MSConnectAccess.conn();
         PreparedStatement pstmt = conn != null ? conn.prepareStatement(sql) : null;
         ResultSet rs = pstmt != null ? pstmt.executeQuery() : null) {

        if (conn == null || rs == null) {
            return;
        }

        while (rs.next()) {
            Object[] row = {
                rs.getString("ID"),
                rs.getString("product_name"),
                rs.getDouble("price"),
                rs.getInt("quantity")
            };
            model.addRow(row);
        }
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Error loading data: " + e.getMessage(), "Database Error", JOptionPane.ERROR_MESSAGE);
    }
}


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnadd;
    private javax.swing.JButton btnclear;
    private javax.swing.JButton btndelete;
    private javax.swing.JButton btnupdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtprice;
    private javax.swing.JTextField txtproduct_name;
    private javax.swing.JTextField txtquantity;
    // End of variables declaration//GEN-END:variables
}
