/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.inong_act2a;

/**
 *
 * @author CL2-PC
 */
public class rps_form extends javax.swing.JFrame {

    /**
     * Creates new form rps_form
     */
    public rps_form() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl1 = new javax.swing.JLabel();
        btn3 = new javax.swing.JButton();
        btn6 = new javax.swing.JButton();
        btn7 = new javax.swing.JButton();
        btn8 = new javax.swing.JButton();
        btn9 = new javax.swing.JButton();
        btn10 = new javax.swing.JButton();
        btn11 = new javax.swing.JButton();
        btn12 = new javax.swing.JButton();
        btn13 = new javax.swing.JButton();
        btn14 = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btn15 = new javax.swing.JButton();
        btn16 = new javax.swing.JButton();
        btn17 = new javax.swing.JButton();
        btn18 = new javax.swing.JButton();
        btn19 = new javax.swing.JButton();
        btn20 = new javax.swing.JButton();
        btn21 = new javax.swing.JButton();
        btn22 = new javax.swing.JButton();
        btn23 = new javax.swing.JButton();
        btn24 = new javax.swing.JButton();
        btn25 = new javax.swing.JButton();
        btn26 = new javax.swing.JButton();
        btn27 = new javax.swing.JButton();
        btn28 = new javax.swing.JButton();
        btn29 = new javax.swing.JButton();
        btn30 = new javax.swing.JButton();
        btn31 = new javax.swing.JButton();
        btn32 = new javax.swing.JButton();
        btn33 = new javax.swing.JButton();
        btn34 = new javax.swing.JButton();
        btn35 = new javax.swing.JButton();
        btn36 = new javax.swing.JButton();
        btn37 = new javax.swing.JButton();
        btn38 = new javax.swing.JButton();
        btn39 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        lbl2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbl1.setText("0");
        getContentPane().add(lbl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 100, 30, 30));

        btn3.setBackground(new java.awt.Color(51, 204, 255));
        btn3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn3.setText("=");
        getContentPane().add(btn3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 480, 60, 30));

        btn6.setText(".");
        getContentPane().add(btn6, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 480, 60, 30));

        btn7.setText("0");
        getContentPane().add(btn7, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 480, 60, 30));

        btn8.setText("+/-");
        getContentPane().add(btn8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 480, 60, 30));

        btn9.setText("In");
        getContentPane().add(btn9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 480, 60, 30));

        btn10.setText("log");
        getContentPane().add(btn10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 440, 60, 30));

        btn11.setText("1");
        getContentPane().add(btn11, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 440, 60, 30));

        btn12.setText("2");
        getContentPane().add(btn12, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 440, 60, 30));

        btn13.setText("3");
        getContentPane().add(btn13, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 440, 60, 30));

        btn14.setText("10x");
        getContentPane().add(btn14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, 60, 30));

        btn4.setText("4");
        getContentPane().add(btn4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 400, 60, 30));

        btn15.setText("5");
        getContentPane().add(btn15, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 400, 60, 30));

        btn16.setText("6");
        getContentPane().add(btn16, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 400, 60, 30));

        btn17.setText("mod");
        getContentPane().add(btn17, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 280, 60, 30));

        btn18.setText("xy");
        getContentPane().add(btn18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 60, 30));

        btn19.setText("7");
        getContentPane().add(btn19, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 360, 60, 30));

        btn20.setText("8");
        getContentPane().add(btn20, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 360, 60, 30));

        btn21.setText("9");
        getContentPane().add(btn21, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 360, 60, 30));

        btn22.setText("-");
        getContentPane().add(btn22, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 400, 60, 30));

        btn23.setText("2 √x");
        getContentPane().add(btn23, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 60, 30));

        btn24.setText("x2");
        btn24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn24ActionPerformed(evt);
            }
        });
        getContentPane().add(btn24, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 60, 30));

        btn25.setText("2nd");
        getContentPane().add(btn25, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 60, 30));

        btn26.setText("(");
        getContentPane().add(btn26, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 320, 60, 30));

        btn27.setText(")");
        getContentPane().add(btn27, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 320, 60, 30));

        btn28.setText("n!");
        getContentPane().add(btn28, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 320, 60, 30));

        btn29.setText("x");
        getContentPane().add(btn29, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 360, 60, 30));

        btn30.setText("1/x");
        getContentPane().add(btn30, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, 60, 30));

        btn31.setText("|x|");
        getContentPane().add(btn31, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 280, 60, 30));

        btn32.setText("exp");
        getContentPane().add(btn32, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 280, 60, 30));

        btn33.setText("÷");
        getContentPane().add(btn33, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 320, 60, 30));

        btn34.setText("π");
        getContentPane().add(btn34, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 240, 60, 30));

        btn35.setText("e");
        getContentPane().add(btn35, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 240, 60, 30));

        btn36.setText("C");
        getContentPane().add(btn36, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 240, 60, 30));

        btn37.setText("⌫");
        getContentPane().add(btn37, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 240, 60, 30));

        btn38.setText("+");
        getContentPane().add(btn38, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 440, 60, 30));

        btn39.setText("+");
        getContentPane().add(btn39, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 440, 60, 30));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Function" }));
        jComboBox1.setName("trigonometry\n"); // NOI18N
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 200, 90, 30));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Trigonometry", "2nd", "sin", "cos", "tan", "hyp", "sec", "csc", "cot", " ", " " }));
        jComboBox2.setName("trigonometry\n"); // NOI18N
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 110, 30));

        jLabel1.setText("M↓");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 170, 30, -1));

        jLabel2.setText("MC");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 30, -1));

        jLabel3.setText("MR");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, 30, -1));

        jLabel4.setText("M+");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, 30, -1));

        jLabel5.setText("MS");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 170, 30, -1));

        jButton1.setText("F-E");
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, 60, -1));

        jButton2.setText("DEG");
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 60, -1));

        lbl2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl2.setText("≡SCIENTIFIC");
        getContentPane().add(lbl2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 150, -1));

        jLabel6.setText("🕒");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 20, -1, -1));

        jLabel7.setText("M-");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 170, 30, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn24ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn24ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(rps_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(rps_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(rps_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(rps_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new rps_form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn10;
    private javax.swing.JButton btn11;
    private javax.swing.JButton btn12;
    private javax.swing.JButton btn13;
    private javax.swing.JButton btn14;
    private javax.swing.JButton btn15;
    private javax.swing.JButton btn16;
    private javax.swing.JButton btn17;
    private javax.swing.JButton btn18;
    private javax.swing.JButton btn19;
    private javax.swing.JButton btn20;
    private javax.swing.JButton btn21;
    private javax.swing.JButton btn22;
    private javax.swing.JButton btn23;
    private javax.swing.JButton btn24;
    private javax.swing.JButton btn25;
    private javax.swing.JButton btn26;
    private javax.swing.JButton btn27;
    private javax.swing.JButton btn28;
    private javax.swing.JButton btn29;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn30;
    private javax.swing.JButton btn31;
    private javax.swing.JButton btn32;
    private javax.swing.JButton btn33;
    private javax.swing.JButton btn34;
    private javax.swing.JButton btn35;
    private javax.swing.JButton btn36;
    private javax.swing.JButton btn37;
    private javax.swing.JButton btn38;
    private javax.swing.JButton btn39;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn6;
    private javax.swing.JButton btn7;
    private javax.swing.JButton btn8;
    private javax.swing.JButton btn9;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel lbl1;
    private javax.swing.JLabel lbl2;
    // End of variables declaration//GEN-END:variables
}
